### ISSUE TITLE
TypeError: run() got an unexpected keyword argument 'stream'

### ISSUE THREAD

**Issue by benzkji** [tarekziade/salvo#5]
I tried both salvo from pypi, and a `-e` install from the current master (that is as well 0.1, as I discovered ;-) 

```
--- ~ » salvo -c 10 -n 100 https://bnzk.ch                            
-------- Server info --------

Server Software: nginx

-------- Running 100 queries - concurrency 10 --------


Traceback (most recent call last):
  File "/home/benzkji/.local/bin/salvo", line 11, in <module>
    load_entry_point('salvo', 'console_scripts', 'salvo')()
  File "/home/benzkji/src/salvo/salvo/run.py", line 203, in main
    res, molotov_res = load(url, args)
  File "/home/benzkji/src/salvo/salvo/run.py", line 41, in load
    molotov_res = run_test(url, res, args)
  File "/home/benzkji/src/salvo/salvo/scenario.py", line 114, in run_test
    res = run(args, stream=stream)
TypeError: run() got an unexpected keyword argument 'stream'

**Comment by tarekziade** [comment]
oh yeah I forgot to release Molotov. Will do right away

**Comment by benzkji** [comment]
yeas thanks!

**Comment by tarekziade** [comment]
done, please update Molotov to 2.1 and let me know

**Comment by benzkji** [comment]
there it goes, perfect. thank you!

**Comment by tarekziade** [comment]
awesome! thanks for letting me know. Happy breaking!

**Comment by benzkji** [comment]
:-)
