### ISSUE TITLE
got an unexpected keyword argument 'loop'

### ISSUE THREAD

**Issue by kalimalrazif** [tarekziade/salvo#8]
Hi:

I want to use salvo on my project, install it with pipenv and run against my apache server and got this error:

```❯ salvo http://127.0.0.1:9080/ -c 10 -n 100
-------- Server info --------

Server Software: Apache/2.4.41 (Ubuntu)

-------- Running 100 queries - concurrency 10 --------


Traceback (most recent call last):
  File "/home/nomar/.local/share/virtualenvs/fastapi_blueprint_01-Z-nbJPAX/bin/salvo", line 8, in <module>
    sys.exit(console_main())
  File "/home/nomar/.local/share/virtualenvs/fastapi_blueprint_01-Z-nbJPAX/lib/python3.10/site-packages/salvo/run.py", line 221, in console_main
    main()
  File "/home/nomar/.local/share/virtualenvs/fastapi_blueprint_01-Z-nbJPAX/lib/python3.10/site-packages/salvo/run.py", line 200, in main
    res, molotov_res = load(args.url, args)
  File "/home/nomar/.local/share/virtualenvs/fastapi_blueprint_01-Z-nbJPAX/lib/python3.10/site-packages/salvo/run.py", line 44, in load
    molotov_res = run_test(url, res, args)
  File "/home/nomar/.local/share/virtualenvs/fastapi_blueprint_01-Z-nbJPAX/lib/python3.10/site-packages/salvo/scenario.py", line 139, in run_test
    res = run(args, stream=stream)
  File "/home/nomar/.local/share/virtualenvs/fastapi_blueprint_01-Z-nbJPAX/lib/python3.10/site-packages/molotov/run.py", line 301, in run
    res = Runner(args)()
  File "/home/nomar/.local/share/virtualenvs/fastapi_blueprint_01-Z-nbJPAX/lib/python3.10/site-packages/molotov/runner.py", line 73, in __call__
    return self._launch_processes()
  File "/home/nomar/.local/share/virtualenvs/fastapi_blueprint_01-Z-nbJPAX/lib/python3.10/site-packages/molotov/runner.py", line 119, in _launch_processes
    self._process()
  File "/home/nomar/.local/share/virtualenvs/fastapi_blueprint_01-Z-nbJPAX/lib/python3.10/site-packages/molotov/runner.py", line 199, in _process
    display = self.gather(update, display)
  File "/home/nomar/.local/share/virtualenvs/fastapi_blueprint_01-Z-nbJPAX/lib/python3.10/site-packages/molotov/runner.py", line 57, in gather
    return asyncio.gather(*futures, loop=self.loop, return_exceptions=True)
TypeError: gather() got an unexpected keyword argument 'loop'
```

Any advice? 

Thanks in advance
Nomar Mora

**Comment by n1ngu** [comment]
This is a molotov issue. You might want to close this and watch https://github.com/loads/molotov/issues/137

As a workaround, use python<3.10 due to https://github.com/python/cpython/issues/86558

**Comment by kalimalrazif** [comment]
Thanks :-) I will :-)

**Comment by kalimalrazif** [comment]
Thanks :-) I will :-)

**Comment by kalimalrazif** [comment]
Thanks :-) I will :-)
